### ISSUE TITLE
Builder image doesn't work out of the box

### ISSUE THREAD

**Issue by jarifibrahim** [sclorg/golang-container#21] opened 2019-01-31 14:47 UTC
Hi, I'm trying to build https://github.com/jarifibrahim/golang-health-check/tree/without-s2i using the command
```
➜  golang-health-check git:(without-s2i) s2i build . centos/go-toolset-7-centos7:latest test-app                                                                   
/tmp/src ~
This is a S2I golang-1.10 centos base image:
To use it, install S2I: https://github.com/openshift/source-to-image
Sample invocation:
s2i build -e IMPORT_URL='github.com/cpuguy83/go-md2man' git://github.com/cpuguy83/go-md2man centos/golang-1.10-centos go-sample-app
You can then run the resulting image via:
docker run go-sample-app
Build completed successfully
➜  golang-health-check git:(without-s2i) docker run test-app         
/usr/libexec/s2i/run: line 5: /opt/app-root/gobinary: No such file or directory
➜  golang-health-check git:(without-s2i) 
```

The assemble script succeeds without any error or explanation but the built container doesn't work.

**Comment by jcajka** [comment] 2019-01-31 16:22
It seems that the upstream project is providing its own assemble script, which means that this is not an issue related to this repository as the upstream project never supported building with the stock assemble script.
Anyway I will check it out of my curiosity as the project seems simple enough.

**Comment by jarifibrahim** [comment] 2019-01-31 16:57
>It seems that the upstream project is providing its own assemble script, which means that this is not an issue related to this repository as the upstream project never supported building with the stock assemble script.

I am the maintainer of  https://github.com/jarifibrahim/golang-health-check :)
I had to add the custom s2i scripts because the default ones didn't work for us. You can try the `without-s2i` branch, it doesn't have the custom assemble and run script.

**Comment by jcajka** [comment] 2019-02-01 09:07
@jarifibrahim I don't know that ;) You have pointed me to your fork.
Digging bit deeper it seems that you are not setting the ```IMPORT_URL``` env var as described in the usage printed. With it set  properly it builds fine ```-e IMPORT_URL='github.com/jarifibrahim/golang-health-check'```. When it is not set we can't really infer what it built 

The assembler script should error out with better error messages and better handled edge cases. I will try to look in to that today for this upstream repo(can't promise that it will ever make its way in to the centos).

**Comment by jcajka** [comment] 2019-02-01 09:46
@jarifibrahim Issue for the golang(notably it is compiled in contrast to the node and hasn't had build in package manager) in many cases is that you need to know what are you building therefor the import_url. In most cases(I need to investigate go mods&co if it is possible to infer the import url from the metadata in the repo) it can't be inferred and by design the s2i is not exposing the URI with sources built, witch would help a lot with the inference. Current assemble script supports only simple projects with fully resolved dependencies without the import_url set.

**Comment by jcajka** [comment] 2019-02-01 10:04
Oh anf GOPATH that needs to be prepared is/was core part of the build.

**Comment by jarifibrahim** [comment] 2019-02-01 10:04
>Current assemble script supports only simple projects with fully resolved dependencies without the import_url set.

Ah, okay.

**Comment by jcajka** [comment] 2019-02-01 15:08
I have submitted/will submit two PRs one that improves the error message and other adding capability to extract the needed meta data from the [Go module](https://blog.golang.org/modules2019), tl;dr; ```go mod init <IMPORT_URL>``` in the root of the Go project. 

I will close this issue and let's talk more off github.

**Closed by jcajka** 2019-02-01 15:08 UTC
