### ISSUE TITLE
Golang version tags in image

### ISSUE THREAD

**Issue by jarifibrahim** [sclorg/golang-container#24] opened 2019-03-28 04:45 UTC
Currently, the images are tagged as `latest` and this makes it very difficult to figure out which version of golang is being used. It would be very useful if we could tag the images with go version.

For instance, `centos/go-toolset-7-centos7:1.10` shows which version of golang is installed compared to `centos/go-toolset-7-centos7/`. 

We use the centos image in https://github.com/golang-starters/golang-http-crud/blob/master/.openshiftio/application.yaml#L46 and there is a possibility that the project wouldn't build if the centos image was rebuilt and the go version changed from go 1.10 to 1.11.

Adding a version tag would be a minor change but it would be immensely useful.

cc @sbose78 @ALRubinger

**Comment by jarifibrahim** [comment] 2019-03-28 04:52
@jcajka What do you think?

**Comment by ALRubinger** [comment] 2019-03-28 13:09
Would appreciate this so we may depend upon guaranteed versions over time and explicitly upgrade our dependencies.  Thank you!

**Comment by pkubatrh** [comment] 2019-04-02 05:54
Closing as duplicate of #20

**Closed by pkubatrh** 2019-04-02 05:54 UTC
